# Generated by Django 4.1.3 on 2024-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUGALLERY', '0004_multipleimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static\x07ssets\\img\x0cavicon.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.CharField(default='place', max_length=255),
        ),
    ]
