# Generated by Django 4.1.3 on 2024-01-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDUGALLERY', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
