# Generated by Django 4.1.3 on 2024-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUGALLERY', '0008_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.BigIntegerField(default='0000000000'),
        ),
    ]
